### ISSUE TITLE
gateway_mfr isn't properly included

### ISSUE THREAD

**Issue by vpetersson** [NebraLtd/hm-pyhelper#18]
I just [deployed](https://github.com/NebraLtd/helium-miner-software/commit/d0a8c7ff43a8282eb968a433383556faa12706b8) the latest hm-diag, which [includes](https://github.com/NebraLtd/hm-diag/blob/master/requirements.txt#L8) hm-pyhelper. However, it isn't working at this point.

```
>>> from hm_pyhelper.miner_param import get_public_keys_rust
>>> get_public_keys_rust()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/hm_pyhelper/miner_param.py", line 15, in get_public_keys_rust
    run_gateway_mfr_keys = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.8/site-packages/hm_pyhelper/gateway_mfr'
```

**Comment by vpetersson** [comment]
This looks like the issue:
https://github.com/NebraLtd/hm-pyhelper/runs/3666503217?check_suite_focus=true#step:7:66
