### ISSUE TITLE
ECC detected still shows as true when hm-pyhelper is failing to find gateway_mfr

### ISSUE THREAD

**Issue by shawaj** [NebraLtd/hm-pyhelper#216]
```
 diagnostics  2023-02-05 17:10:01,523 - [INFO] - hw_diag.utilities.hardware - (hardware.py).get_lte_devices -- /opt/python-dependencies/hw_diag/utilities/hardware.py:(174) - Found the following LTE Devices: [{'Model': 'QUECTEL Mobile Broadband Module', 'Manufacturer': 'QUALCOMM INCORPORATED', 'EquipmentIdentifier': '867698042982846'}]
 diagnostics  INFO:hw_diag.utilities.hardware:Found the following LTE Devices: [{'Model': 'QUECTEL Mobile Broadband Module', 'Manufacturer': 'QUALCOMM INCORPORATED', 'EquipmentIdentifier': '867698042982846'}]
 diagnostics  INFO:root:Frequency: EU868
 diagnostics  
 diagnostics  INFO:root:Diagnostics shipping not requested, skipping.
 diagnostics  INFO:root:Diagnostics complete
 diagnostics  DEBUG:urllib3.connectionpool:https://o571444.ingest.sentry.io:443 "POST /api/5730184/envelope/ HTTP/1.1" 200 2
 diagnostics  INFO:root:Running periodic hardware diagnostics
 diagnostics  2023-02-05 17:11:01,651 - [ERROR] - hm_pyhelper.miner_param - (miner_param.py).get_gateway_mfr_version -- /opt/python-dependencies/hm_pyhelper/miner_param.py:(89) - Exception occurred on running gateway_mfr --version: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 82, in get_gateway_mfr_version
 diagnostics      run_gateway_mfr_result = subprocess.run(
 diagnostics                               ^^^^^^^^^^^^^^^
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 548, in run
 diagnostics      with Popen(*popenargs, **kwargs) as process:
 diagnostics           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 diagnostics    File "/opt/python-dependencies/sentry_sdk/integrations/stdlib.py", line 200, in sentry_patched_popen_init
 diagnostics      rv = old_popen_init(self, *a, **kw)
 diagnostics           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 1024, in __init__
 diagnostics      self._execute_child(args, executable, preexec_fn, close_fds,
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 1901, in _execute_child
 diagnostics      raise child_exception_type(errno_num, err_msg, err_filename)
 diagnostics  FileNotFoundError: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  ERROR:hm_pyhelper.miner_param:Exception occurred on running gateway_mfr --version: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 82, in get_gateway_mfr_version
 diagnostics      run_gateway_mfr_result = subprocess.run(
 diagnostics                               ^^^^^^^^^^^^^^^
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 548, in run
 diagnostics      with Popen(*popenargs, **kwargs) as process:
 diagnostics           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 diagnostics    File "/opt/python-dependencies/sentry_sdk/integrations/stdlib.py", line 200, in sentry_patched_popen_init
 diagnostics      rv = old_popen_init(self, *a, **kw)
 diagnostics           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 1024, in __init__
 diagnostics      self._execute_child(args, executable, preexec_fn, close_fds,
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 1901, in _execute_child
 diagnostics      raise child_exception_type(errno_num, err_msg, err_filename)
 diagnostics  FileNotFoundError: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  2023-02-05 17:11:01,691 - [ERROR] - hw_diag.utilities.hardware - (hardware.py).get_public_keys_and_ignore_errors -- /opt/python-dependencies/hw_diag/utilities/hardware.py:(297) - Exception occurred on running gateway_mfr --version: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  ERROR:hw_diag.utilities.hardware:Exception occurred on running gateway_mfr --version: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  2023-02-05 17:11:01,708 - [INFO] - hw_diag.utilities.hardware - (hardware.py).get_ble_devices -- /opt/python-dependencies/hw_diag/utilities/hardware.py:(81) - Retrieving list of BLE device(s)
 diagnostics  INFO:hw_diag.utilities.hardware:Retrieving list of BLE device(s)
 diagnostics  2023-02-05 17:11:01,718 - [INFO] - hw_diag.utilities.hardware - (hardware.py).get_ble_devices -- /opt/python-dependencies/hw_diag/utilities/hardware.py:(101) - Found the following BLE Devices: [{'Address': '00:1A:7D:DA:71:13', 'Name': 'nebra-EF6DE7.local', 'Powered': '1', 'Discoverable': '0', 'Pairable': '0', 'Discovering': '0'}]
 diagnostics  INFO:hw_diag.utilities.hardware:Found the following BLE Devices: [{'Address': '00:1A:7D:DA:71:13', 'Name': 'nebra-EF6DE7.local', 'Powered': '1', 'Discoverable': '0', 'Pairable': '0', 'Discovering': '0'}]
 diagnostics  2023-02-05 17:11:01,719 - [INFO] - hw_diag.utilities.hardware - (hardware.py).get_lte_devices -- /opt/python-dependencies/hw_diag/utilities/hardware.py:(147) - Retrieving list of LTE device(s)
 diagnostics  INFO:hw_diag.utilities.hardware:Retrieving list of LTE device(s)
 diagnostics  DEBUG:urllib3.connectionpool:https://o571444.ingest.sentry.io:443 "POST /api/5730184/store/ HTTP/1.1" 429 198
 diagnostics  2023-02-05 17:11:01,756 - [INFO] - hw_diag.utilities.hardware - (hardware.py).get_lte_devices -- /opt/python-dependencies/hw_diag/utilities/hardware.py:(174) - Found the following LTE Devices: [{'Model': 'QUECTEL Mobile Broadband Module', 'Manufacturer': 'QUALCOMM INCORPORATED', 'EquipmentIdentifier': '867698042982846'}]
 diagnostics  INFO:hw_diag.utilities.hardware:Found the following LTE Devices: [{'Model': 'QUECTEL Mobile Broadband Module', 'Manufacturer': 'QUALCOMM INCORPORATED', 'EquipmentIdentifier': '867698042982846'}]
 diagnostics  INFO:root:Frequency: EU868
 diagnostics  
 diagnostics  INFO:root:Diagnostics shipping not requested, skipping.
 diagnostics  INFO:root:Diagnostics complete
 diagnostics  INFO:root:Running periodic hardware diagnostics
 diagnostics  2023-02-05 17:11:04,226 - [ERROR] - hm_pyhelper.miner_param - (miner_param.py).get_gateway_mfr_version -- /opt/python-dependencies/hm_pyhelper/miner_param.py:(89) - Exception occurred on running gateway_mfr --version: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 82, in get_gateway_mfr_version
 diagnostics      run_gateway_mfr_result = subprocess.run(
 diagnostics                               ^^^^^^^^^^^^^^^
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 548, in run
 diagnostics      with Popen(*popenargs, **kwargs) as process:
 diagnostics           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 diagnostics    File "/opt/python-dependencies/sentry_sdk/integrations/stdlib.py", line 200, in sentry_patched_popen_init
 diagnostics      rv = old_popen_init(self, *a, **kw)
 diagnostics           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 1024, in __init__
 diagnostics      self._execute_child(args, executable, preexec_fn, close_fds,
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 1901, in _execute_child
 diagnostics      raise child_exception_type(errno_num, err_msg, err_filename)
 diagnostics  FileNotFoundError: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  ERROR:hm_pyhelper.miner_param:Exception occurred on running gateway_mfr --version: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 82, in get_gateway_mfr_version
 diagnostics      run_gateway_mfr_result = subprocess.run(
 diagnostics                               ^^^^^^^^^^^^^^^
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 548, in run
 diagnostics      with Popen(*popenargs, **kwargs) as process:
 diagnostics           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 diagnostics    File "/opt/python-dependencies/sentry_sdk/integrations/stdlib.py", line 200, in sentry_patched_popen_init
 diagnostics      rv = old_popen_init(self, *a, **kw)
 diagnostics           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 1024, in __init__
 diagnostics      self._execute_child(args, executable, preexec_fn, close_fds,
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 1901, in _execute_child
 diagnostics      raise child_exception_type(errno_num, err_msg, err_filename)
 diagnostics  FileNotFoundError: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  2023-02-05 17:11:04,268 - [ERROR] - hw_diag.utilities.hardware - (hardware.py).get_public_keys_and_ignore_errors -- /opt/python-dependencies/hw_diag/utilities/hardware.py:(297) - Exception occurred on running gateway_mfr --version: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  ERROR:hw_diag.utilities.hardware:Exception occurred on running gateway_mfr --version: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  2023-02-05 17:11:04,280 - [INFO] - hw_diag.utilities.hardware - (hardware.py).get_ble_devices -- /opt/python-dependencies/hw_diag/utilities/hardware.py:(81) - Retrieving list of BLE device(s)
 diagnostics  INFO:hw_diag.utilities.hardware:Retrieving list of BLE device(s)
 diagnostics  2023-02-05 17:11:04,289 - [INFO] - hw_diag.utilities.hardware - (hardware.py).get_ble_devices -- /opt/python-dependencies/hw_diag/utilities/hardware.py:(101) - Found the following BLE Devices: [{'Address': '00:1A:7D:DA:71:13', 'Name': 'nebra-EF6DE7.local', 'Powered': '1', 'Discoverable': '0', 'Pairable': '0', 'Discovering': '0'}]
 diagnostics  INFO:hw_diag.utilities.hardware:Found the following BLE Devices: [{'Address': '00:1A:7D:DA:71:13', 'Name': 'nebra-EF6DE7.local', 'Powered': '1', 'Discoverable': '0', 'Pairable': '0', 'Discovering': '0'}]
 diagnostics  2023-02-05 17:11:04,290 - [INFO] - hw_diag.utilities.hardware - (hardware.py).get_lte_devices -- /opt/python-dependencies/hw_diag/utilities/hardware.py:(147) - Retrieving list of LTE device(s)
 diagnostics  INFO:hw_diag.utilities.hardware:Retrieving list of LTE device(s)
 diagnostics  2023-02-05 17:11:04,326 - [INFO] - hw_diag.utilities.hardware - (hardware.py).get_lte_devices -- /opt/python-dependencies/hw_diag/utilities/hardware.py:(174) - Found the following LTE Devices: [{'Model': 'QUECTEL Mobile Broadband Module', 'Manufacturer': 'QUALCOMM INCORPORATED', 'EquipmentIdentifier': '867698042982846'}]
 diagnostics  INFO:hw_diag.utilities.hardware:Found the following LTE Devices: [{'Model': 'QUECTEL Mobile Broadband Module', 'Manufacturer': 'QUALCOMM INCORPORATED', 'EquipmentIdentifier': '867698042982846'}]
 diagnostics  INFO:root:Frequency: EU868
 diagnostics  
 diagnostics  INFO:root:Diagnostics shipping not requested, skipping.
 diagnostics  INFO:root:Diagnostics complete
 diagnostics  DEBUG:urllib3.connectionpool:https://o571444.ingest.sentry.io:443 "POST /api/5730184/envelope/ HTTP/1.1" 200 2
 diagnostics  INFO:root:Running periodic hardware diagnostics
 diagnostics  2023-02-05 17:12:01,873 - [ERROR] - hm_pyhelper.miner_param - (miner_param.py).get_gateway_mfr_version -- /opt/python-dependencies/hm_pyhelper/miner_param.py:(89) - Exception occurred on running gateway_mfr --version: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 82, in get_gateway_mfr_version
 diagnostics      run_gateway_mfr_result = subprocess.run(
 diagnostics                               ^^^^^^^^^^^^^^^
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 548, in run
 diagnostics      with Popen(*popenargs, **kwargs) as process:
 diagnostics           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 diagnostics    File "/opt/python-dependencies/sentry_sdk/integrations/stdlib.py", line 200, in sentry_patched_popen_init
 diagnostics      rv = old_popen_init(self, *a, **kw)
 diagnostics           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 1024, in __init__
 diagnostics      self._execute_child(args, executable, preexec_fn, close_fds,
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 1901, in _execute_child
 diagnostics      raise child_exception_type(errno_num, err_msg, err_filename)
 diagnostics  FileNotFoundError: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  ERROR:hm_pyhelper.miner_param:Exception occurred on running gateway_mfr --version: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 82, in get_gateway_mfr_version
 diagnostics      run_gateway_mfr_result = subprocess.run(
 diagnostics                               ^^^^^^^^^^^^^^^
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 548, in run
 diagnostics      with Popen(*popenargs, **kwargs) as process:
 diagnostics           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 diagnostics    File "/opt/python-dependencies/sentry_sdk/integrations/stdlib.py", line 200, in sentry_patched_popen_init
 diagnostics      rv = old_popen_init(self, *a, **kw)
 diagnostics           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 1024, in __init__
 diagnostics      self._execute_child(args, executable, preexec_fn, close_fds,
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 1901, in _execute_child
 diagnostics      raise child_exception_type(errno_num, err_msg, err_filename)
 diagnostics  FileNotFoundError: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  2023-02-05 17:12:01,915 - [ERROR] - hw_diag.utilities.hardware - (hardware.py).get_public_keys_and_ignore_errors -- /opt/python-dependencies/hw_diag/utilities/hardware.py:(297) - Exception occurred on running gateway_mfr --version: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  ERROR:hw_diag.utilities.hardware:Exception occurred on running gateway_mfr --version: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  2023-02-05 17:12:01,928 - [INFO] - hw_diag.utilities.hardware - (hardware.py).get_ble_devices -- /opt/python-dependencies/hw_diag/utilities/hardware.py:(81) - Retrieving list of BLE device(s)
 diagnostics  INFO:hw_diag.utilities.hardware:Retrieving list of BLE device(s)
 diagnostics  2023-02-05 17:12:01,937 - [INFO] - hw_diag.utilities.hardware - (hardware.py).get_ble_devices -- /opt/python-dependencies/hw_diag/utilities/hardware.py:(101) - Found the following BLE Devices: [{'Address': '00:1A:7D:DA:71:13', 'Name': 'nebra-EF6DE7.local', 'Powered': '1', 'Discoverable': '0', 'Pairable': '0', 'Discovering': '0'}]
 diagnostics  INFO:hw_diag.utilities.hardware:Found the following BLE Devices: [{'Address': '00:1A:7D:DA:71:13', 'Name': 'nebra-EF6DE7.local', 'Powered': '1', 'Discoverable': '0', 'Pairable': '0', 'Discovering': '0'}]
 diagnostics  2023-02-05 17:12:01,938 - [INFO] - hw_diag.utilities.hardware - (hardware.py).get_lte_devices -- /opt/python-dependencies/hw_diag/utilities/hardware.py:(147) - Retrieving list of LTE device(s)
 diagnostics  INFO:hw_diag.utilities.hardware:Retrieving list of LTE device(s)
 diagnostics  2023-02-05 17:12:01,976 - [INFO] - hw_diag.utilities.hardware - (hardware.py).get_lte_devices -- /opt/python-dependencies/hw_diag/utilities/hardware.py:(174) - Found the following LTE Devices: [{'Model': 'QUECTEL Mobile Broadband Module', 'Manufacturer': 'QUALCOMM INCORPORATED', 'EquipmentIdentifier': '867698042982846'}]
 diagnostics  INFO:hw_diag.utilities.hardware:Found the following LTE Devices: [{'Model': 'QUECTEL Mobile Broadband Module', 'Manufacturer': 'QUALCOMM INCORPORATED', 'EquipmentIdentifier': '867698042982846'}]
 diagnostics  INFO:root:Frequency: EU868
 diagnostics  
 diagnostics  INFO:root:Diagnostics shipping not requested, skipping.
 diagnostics  INFO:root:Diagnostics complete
 diagnostics  DEBUG:urllib3.connectionpool:https://o571444.ingest.sentry.io:443 "POST /api/5730184/envelope/ HTTP/1.1" 200 2
 diagnostics  INFO:root:Running periodic hardware diagnostics
 diagnostics  2023-02-05 17:13:02,317 - [ERROR] - hm_pyhelper.miner_param - (miner_param.py).get_gateway_mfr_version -- /opt/python-dependencies/hm_pyhelper/miner_param.py:(89) - Exception occurred on running gateway_mfr --version: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 82, in get_gateway_mfr_version
 diagnostics      run_gateway_mfr_result = subprocess.run(
 diagnostics                               ^^^^^^^^^^^^^^^
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 548, in run
 diagnostics      with Popen(*popenargs, **kwargs) as process:
 diagnostics           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 diagnostics    File "/opt/python-dependencies/sentry_sdk/integrations/stdlib.py", line 200, in sentry_patched_popen_init
 diagnostics      rv = old_popen_init(self, *a, **kw)
 diagnostics           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 1024, in __init__
 diagnostics      self._execute_child(args, executable, preexec_fn, close_fds,
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 1901, in _execute_child
 diagnostics      raise child_exception_type(errno_num, err_msg, err_filename)
 diagnostics  FileNotFoundError: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  ERROR:hm_pyhelper.miner_param:Exception occurred on running gateway_mfr --version: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 82, in get_gateway_mfr_version
 diagnostics      run_gateway_mfr_result = subprocess.run(
 diagnostics                               ^^^^^^^^^^^^^^^
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 548, in run
 diagnostics      with Popen(*popenargs, **kwargs) as process:
 diagnostics           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 diagnostics    File "/opt/python-dependencies/sentry_sdk/integrations/stdlib.py", line 200, in sentry_patched_popen_init
 diagnostics      rv = old_popen_init(self, *a, **kw)
 diagnostics           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 1024, in __init__
 diagnostics      self._execute_child(args, executable, preexec_fn, close_fds,
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 1901, in _execute_child
 diagnostics      raise child_exception_type(errno_num, err_msg, err_filename)
 diagnostics  FileNotFoundError: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  2023-02-05 17:13:02,356 - [ERROR] - hw_diag.utilities.hardware - (hardware.py).get_public_keys_and_ignore_errors -- /opt/python-dependencies/hw_diag/utilities/hardware.py:(297) - Exception occurred on running gateway_mfr --version: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  ERROR:hw_diag.utilities.hardware:Exception occurred on running gateway_mfr --version: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  2023-02-05 17:13:02,369 - [INFO] - hw_diag.utilities.hardware - (hardware.py).get_ble_devices -- /opt/python-dependencies/hw_diag/utilities/hardware.py:(81) - Retrieving list of BLE device(s)
 diagnostics  INFO:hw_diag.utilities.hardware:Retrieving list of BLE device(s)
 diagnostics  2023-02-05 17:13:02,377 - [INFO] - hw_diag.utilities.hardware - (hardware.py).get_ble_devices -- /opt/python-dependencies/hw_diag/utilities/hardware.py:(101) - Found the following BLE Devices: [{'Address': '00:1A:7D:DA:71:13', 'Name': 'nebra-EF6DE7.local', 'Powered': '1', 'Discoverable': '0', 'Pairable': '0', 'Discovering': '0'}]
 diagnostics  INFO:hw_diag.utilities.hardware:Found the following BLE Devices: [{'Address': '00:1A:7D:DA:71:13', 'Name': 'nebra-EF6DE7.local', 'Powered': '1', 'Discoverable': '0', 'Pairable': '0', 'Discovering': '0'}]
 diagnostics  2023-02-05 17:13:02,379 - [INFO] - hw_diag.utilities.hardware - (hardware.py).get_lte_devices -- /opt/python-dependencies/hw_diag/utilities/hardware.py:(147) - Retrieving list of LTE device(s)
 diagnostics  INFO:hw_diag.utilities.hardware:Retrieving list of LTE device(s)
 diagnostics  2023-02-05 17:13:02,415 - [INFO] - hw_diag.utilities.hardware - (hardware.py).get_lte_devices -- /opt/python-dependencies/hw_diag/utilities/hardware.py:(174) - Found the following LTE Devices: [{'Model': 'QUECTEL Mobile Broadband Module', 'Manufacturer': 'QUALCOMM INCORPORATED', 'EquipmentIdentifier': '867698042982846'}]
 diagnostics  INFO:hw_diag.utilities.hardware:Found the following LTE Devices: [{'Model': 'QUECTEL Mobile Broadband Module', 'Manufacturer': 'QUALCOMM INCORPORATED', 'EquipmentIdentifier': '867698042982846'}]
 diagnostics  INFO:root:Frequency: EU868
 diagnostics  
 diagnostics  INFO:root:Diagnostics shipping not requested, skipping.
 diagnostics  INFO:root:Diagnostics complete
 diagnostics  DEBUG:urllib3.connectionpool:https://o571444.ingest.sentry.io:443 "POST /api/5730184/envelope/ HTTP/1.1" 200 2
 diagnostics  INFO:root:Running periodic hardware diagnostics
 diagnostics  2023-02-05 17:13:45,998 - [ERROR] - hm_pyhelper.miner_param - (miner_param.py).get_gateway_mfr_version -- /opt/python-dependencies/hm_pyhelper/miner_param.py:(89) - Exception occurred on running gateway_mfr --version: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 82, in get_gateway_mfr_version
 diagnostics      run_gateway_mfr_result = subprocess.run(
 diagnostics                               ^^^^^^^^^^^^^^^
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 548, in run
 diagnostics      with Popen(*popenargs, **kwargs) as process:
 diagnostics           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 diagnostics    File "/opt/python-dependencies/sentry_sdk/integrations/stdlib.py", line 200, in sentry_patched_popen_init
 diagnostics      rv = old_popen_init(self, *a, **kw)
 diagnostics           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 diagnostics  INFO:root:Running periodic hardware diagnostics
 diagnostics  2023-02-05 17:13:50,736 - [ERROR] - hm_pyhelper.miner_param - (miner_param.py).get_gateway_mfr_version -- /opt/python-dependencies/hm_pyhelper/miner_param.py:(89) - Exception occurred on running gateway_mfr --version: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 82, in get_gateway_mfr_version
 diagnostics      run_gateway_mfr_result = subprocess.run(
 diagnostics                               ^^^^^^^^^^^^^^^
 diagnostics  INFO:root:Running periodic hardware diagnostics
 diagnostics  2023-02-05 17:14:02,535 - [ERROR] - hm_pyhelper.miner_param - (miner_param.py).get_gateway_mfr_version -- /opt/python-dependencies/hm_pyhelper/miner_param.py:(89) - Exception occurred on running gateway_mfr --version: [Errno 2] No such file or directory: '/opt/python-dependencies/hm_pyhelper/gateway_mfr'
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 82, in get_gateway_mfr_version
 diagnostics      run_gateway_mfr_result = subprocess.run(
 diagnostics                               ^^^^^^^^^^^^^^^
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 548, in run
 diagnostics      with Popen(*popenargs, **kwargs) as process:
 diagnostics           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
 diagnostics    File "/opt/python-dependencies/sentry_sdk/integrations/stdlib.py", line 200, in sentry_patched_popen_init
 diagnostics      rv = old_popen_init(self, *a, **kw)
 diagnostics           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
<img width="598" alt="image" src="https://user-images.githubusercontent.com/3359418/216833968-4ce05ceb-90e5-4882-8732-346b9ee8b25e.png">

**Comment by shawaj** [comment]
I guess this is to be expected. Given we are only checking for the presence of the ECC by checking the output of i2c.

But maybe we can handle other issues too. Not sure how common this would be in practice though (it only came about by accident)
